export default {
  data: [
    {
      refID: 12345,
      TapID: 123457864,
      name: "Deng Lei",
      email: "Lei@gmail.com",
      blockStatus: "Block User",
      amount: 690,
      currency: "USD",
      country: "Saudi",
      bankfees: -2.15,
      extraCost: -0.27,
      profiting: 678,
      date: "23.10.2022",
      paymentMethod: "Master Card",
      status: "Paid",
      transaction: "url",
    },
    {
      refID: 12345,
      TapID: 123457864,
      name: "Ding Zhilio",
      email: "Zhilio@gmail.com",
      blockStatus: "Unblock User",
      merchantInfo: 690.0,
      amount: 690,
      currency: "USD",
      country: "Non-Saudi",
      bankfees: -2.15,
      extraCost: -0.27,
      profiting: 678,
      date: "23.10.2023",
      paymentMethod: "VISA",
      status: "Unpaid",
      transaction: "url",
    },
    {
      refID: 12345,
      TapID: 123457864,
      name: "Wei Cheng",
      email: "Cheng@gmail.com",
      blockStatus: "Block User",
      merchantInfo: 690.0,
      amount: 690,
      currency: "USD",
      country: "Saudi",
      bankfees: -2.15,
      extraCost: -0.27,
      profiting: 678,
      date: "23.10.2022",
      paymentMethod: "Mada",
      status: "Paid",
      transaction: "url",
    },
  ],
};
